[tool.black]
line-length = 100
target-version = ['py38']
experimental_string_processing = true
preview = true

[tool.isort]
atomic = true
profile = "black"
line_length = 100
skip_gitignore = true
known_first_party = ["black", "blib2to3", "blackd", "_black_version"]
